
[cursor]
unfocused_hollow = false
thickness = 0.1

[cursor.style]
blinking = "Always"
# shape = "Underline"
shape = "Beam"

[debug]
print_events = true

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.glyph_offset]
y = 5

[font.normal]
family = "RobotoMono Nerd Font Mono"

[font.offset]
x = -1
y = 5

[scrolling]
# auto_scroll = true
history = 20000

[window]
decorations = "buttonless"
opacity = 0.98
# startup_mode = "SimpleFullscreen"
startup_mode = "Fullscreen"


[window.dimensions]
columns = 120
lines = 60

[window.padding]
x = 5
y = 5

[general]
# import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]
import = ["~/.config/alacritty/themes/themes/dayfox.toml"]
